openapi: '3.0.3'
info:
  title: Tiket Service API
  version: '1.0'
servers:
  - url: http://157.22.189.188:8085
components:
  schemas:
    Ticket:
      required:
        - id
        - name
        - coordinates
        - creationDate
      type: object
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
          readOnly: true

        name:
          type: string
          minLength: 1

        coordinates:
          $ref: '#/components/schemas/Coordinates'

        creationDate:
          type: string
          format: date
          readOnly: true

        price:
          type: number
          format: double 
          minimum: 0
          exclusiveMinimum: true

        discount:
          type: integer
          format: int64
          minimum: 1
          maximum: 100

        refundable:
          type: boolean

        type:
          type: string
          enum: [VIP, USUAL, CHEAP]
        venue:
          description: 
            Место проведения, может быть как новым, так и существующим. 
            Если передан объект с полями name и capacity, то будет создано новое место проведения.
            Если передан объект с полем id, то будет использовано существующее место проведения с этим id.
          oneOf:
            - $ref: '#/components/schemas/Venue'
            - $ref: '#/components/schemas/ExistingVenue'

    Coordinates:
      type: object
      required:
        - x
        - y
      properties:
        x:
          type: integer
        y:

          type: number
          format: float
          minimum: -341
          exclusiveMinimum: true

    Venue:
      required:
        - id
        - name
      type: object
      properties:
        id:
          type: integer
          readOnly: true
          minimum: 1

        name:
          type: string
          minLength: 1

        capacity:
          type: integer  
          minimum: 1
  
    ExistingVenue:
        required:
          - id
        type: object
        properties:
          id:
            type: integer
            minimum: 1

    TicketSearchRequest:
      type: object
      properties:

        page:
          type: integer
          minimum: 1

        size:
          type: integer
          minimum: 1

        sort:
          type: string

        id:
          type: integer
          format: int64

        name:
          type: string

        creationDate:
          type: string
          format: date

        price:
          type: number
          format: double

        discount:
          type: integer
          format: int64

        refundable:
          type: boolean

        type:
          type: string
          enum: [VIP, USUAL, CHEAP]

        coordinates:
          $ref: '#/components/schemas/Coordinates'

        venue:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
            capacity:
              type: integer
    
    VenueSearchRequest:
      type: object
      properties:
        page:
          type: integer
          minimum: 1

        size:
          type: integer
          minimum: 1

        sort:
          type: string

        id:
          type: integer
          format: int64

        name:
          type: string

        capacity:
          type: integer

    TicketPageResponse:
      type: object
      properties:

        content:
          type: array
          items:
            $ref: '#/components/schemas/Ticket'

        page:
          type: integer
          minimum: 1

        size:
          type: integer
          minimum: 1

        totalElements:
          type: integer
          format: int64
          minimum: 0

        totalPages:
          type: integer
          minimum: 0

        hasNext:
          type: boolean

        hasPrevious:
          type: boolean

    VenuePageResponse:
      type: object
      properties:

        content:
          type: array
          items:
            $ref: '#/components/schemas/Venue'

        page:
          type: integer
          minimum: 1

        size:
          type: integer
          minimum: 1

        totalElements:
          type: integer
          format: int64
          minimum: 0

        totalPages:
          type: integer
          minimum: 0

        hasNext:
          type: boolean

        hasPrevious:
          type: boolean

paths:
  /venues:
    post:
      description: 'Добавить новое место'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Venue'
      responses:
        '201':
          description: Место успешно добавлено
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Venue'
        '400':
          description: Переданы некорректные данные
        '409':
          description: Место с таким name уже существует
  /venues/search:
    post:
      description: 'Поиск, фильтрация, сортировка и постраничный вывод мест проведения'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VenueSearchRequest'
      responses:
        '200':
          description: Результаты поиска получены
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VenuePageResponse'
        '400':
          description: Переданы некорректные параметры поиска
  /venues/{id}:
    get:
      description: 'Получить место по id'
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: Место найдено 
        '400':
          description: Некорректный id
        '404':
          description: Место не найдено
    delete:
      description: 'Удалить место по id'
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '204':
          description: Место успешно удалено
        '400':
          description: Некорректный id
        '404':
          description: Место не найдено
    put:
      description: 'Обновить место по id'
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Venue'
      responses:
        '200':
          description: Место успешно обновлено
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Venue'
        '400':
          description: Переданы некорректные данные
        '404':
          description: Место не найдено
  /tickets:
    post:
      description: 'Добавить новый билет'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Ticket'
      responses:
        '201':
          description: Билет успешно добавлен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ticket'
        '400':
          description: Переданы некорректные данные

  /tickets/{id}:
    get:
      description: 'Получить билет по id'
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: Билет найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ticket'
        '400':
          description: Некорректный id
        '404':
          description: Билет не найден
    
    put:
      description: 'Обновить билет по id'
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Ticket'
      responses:
        '200':
          description: Билет успешно обновлен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ticket'
        '400':
          description: Переданы некорректные данные
        '404':
          description: Билет не найден
    delete:
      description: 'Удалить билет по id'
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '204':
          description: Билет успешно удален
        '400':
          description: Некорректный id
        '404':
          description: Билет не найден

  /tickets/discount/average:
    get:
      description: 'Рассчитать среднее значение discount для всех билетов'
      responses:
        '200':
          description: Среднее значение discount рассчитано
          content:
            application/json:
              schema:
                type: number
                format: double
        '404':
          description: Коллекция билетов пуста
  
  /tickets/latest:
    get:
      description: 'Вернуть билет с максимальным значением creationDate'
      responses:
        '200':
          description: Билет найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ticket'

        '404':
          description: Коллекция билетов пуста

  /tickets/search:
    post:
      description: 'Поиск, фильтрация, сортировка и постраничный вывод билетов'

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TicketSearchRequest'

      responses:
        '200':
          description: Результаты поиска получены
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TicketPageResponse'

        '400':
          description: Переданы некорректные параметры поиска
  /tickets/discount-below/{discount}:
    get:
      description: 'Вернуть билеты, у которых discount меньше заданного значения'

      parameters:
        - name: discount
          in: path
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 100

      responses:
        '200':
          description: Билеты найдены
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ticket'

        '400':
          description: Некорректное значение discount
        '404':
          description: Билеты не найдены
