worker_processes auto;

events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11 valid=10s ipv6=off;
    resolver_timeout 5s;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log warn;

    server {
        listen 80;
        server_name _;

        location ~ ^/api/v1/sso-ident(?:/|$) {
            set $sso_ident_upstream http://sso-ident:8080;

            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_pass $sso_ident_upstream$request_uri;
        }


        location ~ ^/api/v1/inventory(?:/|$) {
            set $inventory_upstream http://inventory:8080;

            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_pass $inventory_upstream$request_uri;
        }


        location ~ ^/api/v1/clients-srv(?:/|$) {
            set $clients_upstream http://clients:8080;

            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_pass $clients_upstream$request_uri;
        }


        location ~ ^/api/v1/tickets(?:/|$) {
            set $tickets_upstream http://tickets:8080;

            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_pass $tickets_upstream$request_uri;
        }

        location / {
            return 404;
        }
    }
}
