- id: inventory-api
  upstream:
    url: http://nginx:80
  match:
    url: <.*/api/v1/inventory(?:/.*)?>
    methods:
      - POST
  authenticators:
    - handler: cookie_session
  authorizer:
    handler: remote_json
    config:
      payload: |
          {
            "namespace": "Service",
            "object": "inventory-service",
            "relation": "access",
            "subject_id": "{{ print .Subject }}"
          }
  mutators:
    - handler: header
